services:
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - ./.n8n:/home/node/.n8n
    env_file:
        - ./.env
    networks:
        - task-network # Red para conectarse a P6

networks:
  task-network:
    name: task-manager-service_default
    external: true